# Test cases automatically generated by Pynguin (https://github.com/se2p/pynguin).
# Please check them before you use them.
import triangle_code as module_0


def test_case_0():
    none_type_0 = None
    int_0 = 750
    str_0 = module_0.triangle(none_type_0, none_type_0, int_0)
    assert str_0 == "Isosceles triangle"


def test_case_1():
    dict_0 = {}
    bool_0 = False
    str_0 = module_0.triangle(dict_0, bool_0, bool_0)
    assert str_0 == "Isosceles triangle"


def test_case_2():
    str_0 = "\x0cS^;uQ696\x0bjJu62o:5k)"
    dict_0 = {str_0: str_0}
    int_0 = -222
    str_1 = module_0.triangle(dict_0, int_0, str_0)
    assert str_1 == "Scalene triangle"
    bool_0 = True
    str_2 = module_0.triangle(bool_0, bool_0, bool_0)
    assert str_2 == "Equilateral triangle"


def test_case_3():
    tuple_0 = ()
    tuple_1 = (tuple_0,)
    str_0 = module_0.triangle(tuple_1, tuple_0, tuple_1)
    assert str_0 == "Isosceles triangle"


def test_case_4():
    bytes_0 = b"g"
    bool_0 = True
    bool_1 = False
    str_0 = module_0.triangle(bytes_0, bool_0, bool_1)
    assert str_0 == "Scalene triangle"
